name: ng2_strap
version: 0.0.1
description: Angular2-Dart Bootstrap directives
author: Luis Vargas <luisvargastijerino@gmail.com>
environment:
  sdk: '>=1.12.0 <2.0.0'
dependencies:
  angular2: ^2.0.0-alpha.46
  browser: ^0.10.0
  bootstrap: ^3.3.4
  node_shims: ^0.1.3
  intl: ^0.12.4+2
  dart_to_js_script_rewriter: ^0.1.0+4
  markdown: ^0.8.0
transformers:
- angular2:
    entry_points: web/index.dart
- dart_to_js_script_rewriter
- $dart2js:
    $include: 'web/index.dart'