name: ng2_strap
version: 0.0.2
description: Angular2-Dart Bootstrap directives
author: Luis Vargas <luisvargastijerino@gmail.com>
homepage: https://github.com/luisvt/ng2-strap
environment:
  sdk: '>=1.12.0 <2.0.0'
dependencies:
  angular2: ^2.0.0-beta.0
  browser: ^0.10.0
  node_shims: ^0.1.3
  intl: ^0.12.4+2
  dart_to_js_script_rewriter: ^0.1.0+4
  markdown: ^0.8.0
  sass: ^0.4.2
  bootstrap_sass: ^3.3.6
transformers:
- sass
- angular2:
    entry_points: web/index.dart
- dart_to_js_script_rewriter
- $dart2js:
    $include: 'web/index.dart'